dataset_root: "./data/Qwen-Qwen2.5-14B-Instruct"
svm_cfg:
  max_iter: 1000
truncate_first_n_tokens: null
truncate_first_n_logits: null
q_tags_to_remove: null
q_tags_to_keep:
  - "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_*"
  - "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_*"
q_tag_transform:
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-A40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-A40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-L40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-L40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-L40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-bfloat16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-L40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-L40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-1_data-parallel-4_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-L40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-flashinfer_speculative-alg-None" : "gpu-NVIDIA-L40"
  "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_dtype-float16_kv-cache-dtype-auto_tensor-parallel-2_data-parallel-2_attn-backend-triton_speculative-alg-None" : "gpu-NVIDIA-L40"
seed: 42
save_dir: "svm/merged-L40-A40_Qwen2.5-14B"