dataset_root: "./data"
svm_cfg:
  max_iter: 1000
truncate_first_n_tokens: null
truncate_first_n_logits: null
q_tags_to_remove: null
q_tags_to_keep:
  - "Qwen-Qwen2.5-14B-Instruct/gpu-NVIDIA-L40_*"
q_tag_transform: null
seed: 42
save_dir: "svm/L40_Qwen2.5-14B"